/* 
 * Amadeus Travel Innovation Sandbox
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace IO.Swagger.Model
{
    /// <summary>
    /// CarrierInfo
    /// </summary>
    [DataContract]
    public partial class CarrierInfo :  IEquatable<CarrierInfo>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CarrierInfo" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CarrierInfo() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CarrierInfo" /> class.
        /// </summary>
        /// <param name="Logos">Logos of the airline in a variety of sizes (required).</param>
        /// <param name="Name">Display name of the airline (required).</param>
        public CarrierInfo(Logos Logos = null, string Name = null)
        {
            // to ensure "Logos" is required (not null)
            if (Logos == null)
            {
                throw new InvalidDataException("Logos is a required property for CarrierInfo and cannot be null");
            }
            else
            {
                this.Logos = Logos;
            }
            // to ensure "Name" is required (not null)
            if (Name == null)
            {
                throw new InvalidDataException("Name is a required property for CarrierInfo and cannot be null");
            }
            else
            {
                this.Name = Name;
            }
        }
        
        /// <summary>
        /// Logos of the airline in a variety of sizes
        /// </summary>
        /// <value>Logos of the airline in a variety of sizes</value>
        [DataMember(Name="logos", EmitDefaultValue=false)]
        public Logos Logos { get; set; }
        /// <summary>
        /// Display name of the airline
        /// </summary>
        /// <value>Display name of the airline</value>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CarrierInfo {\n");
            sb.Append("  Logos: ").Append(Logos).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as CarrierInfo);
        }

        /// <summary>
        /// Returns true if CarrierInfo instances are equal
        /// </summary>
        /// <param name="other">Instance of CarrierInfo to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CarrierInfo other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Logos == other.Logos ||
                    this.Logos != null &&
                    this.Logos.Equals(other.Logos)
                ) && 
                (
                    this.Name == other.Name ||
                    this.Name != null &&
                    this.Name.Equals(other.Name)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Logos != null)
                    hash = hash * 59 + this.Logos.GetHashCode();
                if (this.Name != null)
                    hash = hash * 59 + this.Name.GetHashCode();
                return hash;
            }
        }
    }

}
