/* 
 * Amadeus Travel Innovation Sandbox
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace IO.Swagger.Model
{
    /// <summary>
    /// FareRestrictions
    /// </summary>
    [DataContract]
    public partial class FareRestrictions :  IEquatable<FareRestrictions>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FareRestrictions" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected FareRestrictions() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="FareRestrictions" /> class.
        /// </summary>
        /// <param name="Refundable">Indicates whether this fare is refundable under some circumstances. Note that a refund charge or penalty may apply (required).</param>
        /// <param name="ChangePenalties">Indicates whether this fare allows the itinerary to be changed under some circumstances. Note that a change fee or penalty may apply (required).</param>
        public FareRestrictions(bool? Refundable = null, bool? ChangePenalties = null)
        {
            // to ensure "Refundable" is required (not null)
            if (Refundable == null)
            {
                throw new InvalidDataException("Refundable is a required property for FareRestrictions and cannot be null");
            }
            else
            {
                this.Refundable = Refundable;
            }
            // to ensure "ChangePenalties" is required (not null)
            if (ChangePenalties == null)
            {
                throw new InvalidDataException("ChangePenalties is a required property for FareRestrictions and cannot be null");
            }
            else
            {
                this.ChangePenalties = ChangePenalties;
            }
        }
        
        /// <summary>
        /// Indicates whether this fare is refundable under some circumstances. Note that a refund charge or penalty may apply
        /// </summary>
        /// <value>Indicates whether this fare is refundable under some circumstances. Note that a refund charge or penalty may apply</value>
        [DataMember(Name="refundable", EmitDefaultValue=false)]
        public bool? Refundable { get; set; }
        /// <summary>
        /// Indicates whether this fare allows the itinerary to be changed under some circumstances. Note that a change fee or penalty may apply
        /// </summary>
        /// <value>Indicates whether this fare allows the itinerary to be changed under some circumstances. Note that a change fee or penalty may apply</value>
        [DataMember(Name="change_penalties", EmitDefaultValue=false)]
        public bool? ChangePenalties { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class FareRestrictions {\n");
            sb.Append("  Refundable: ").Append(Refundable).Append("\n");
            sb.Append("  ChangePenalties: ").Append(ChangePenalties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as FareRestrictions);
        }

        /// <summary>
        /// Returns true if FareRestrictions instances are equal
        /// </summary>
        /// <param name="other">Instance of FareRestrictions to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(FareRestrictions other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Refundable == other.Refundable ||
                    this.Refundable != null &&
                    this.Refundable.Equals(other.Refundable)
                ) && 
                (
                    this.ChangePenalties == other.ChangePenalties ||
                    this.ChangePenalties != null &&
                    this.ChangePenalties.Equals(other.ChangePenalties)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Refundable != null)
                    hash = hash * 59 + this.Refundable.GetHashCode();
                if (this.ChangePenalties != null)
                    hash = hash * 59 + this.ChangePenalties.GetHashCode();
                return hash;
            }
        }
    }

}
