/* 
 * Amadeus Travel Innovation Sandbox
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace IO.Swagger.Model
{
    /// <summary>
    /// FlightReservationBound
    /// </summary>
    [DataContract]
    public partial class FlightReservationBound :  IEquatable<FlightReservationBound>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FlightReservationBound" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected FlightReservationBound() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="FlightReservationBound" /> class.
        /// </summary>
        /// <param name="Flights">The individual flights that make up this itinerary. These flights are presented in the order required to fly from the origin to the destination, and the array of flights represents a connection. (required).</param>
        public FlightReservationBound(List<FlightReservationSegment> Flights = null)
        {
            // to ensure "Flights" is required (not null)
            if (Flights == null)
            {
                throw new InvalidDataException("Flights is a required property for FlightReservationBound and cannot be null");
            }
            else
            {
                this.Flights = Flights;
            }
        }
        
        /// <summary>
        /// The individual flights that make up this itinerary. These flights are presented in the order required to fly from the origin to the destination, and the array of flights represents a connection.
        /// </summary>
        /// <value>The individual flights that make up this itinerary. These flights are presented in the order required to fly from the origin to the destination, and the array of flights represents a connection.</value>
        [DataMember(Name="flights", EmitDefaultValue=false)]
        public List<FlightReservationSegment> Flights { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class FlightReservationBound {\n");
            sb.Append("  Flights: ").Append(Flights).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as FlightReservationBound);
        }

        /// <summary>
        /// Returns true if FlightReservationBound instances are equal
        /// </summary>
        /// <param name="other">Instance of FlightReservationBound to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(FlightReservationBound other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Flights == other.Flights ||
                    this.Flights != null &&
                    this.Flights.SequenceEqual(other.Flights)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Flights != null)
                    hash = hash * 59 + this.Flights.GetHashCode();
                return hash;
            }
        }
    }

}
