/* 
 * Amadeus Travel Innovation Sandbox
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Logos
    /// </summary>
    [DataContract]
    public partial class Logos :  IEquatable<Logos>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Logos" /> class.
        /// </summary>
        /// <param name="Small">URL to logo of resolution 27x27px.</param>
        /// <param name="Medium">URL to logo of resolution 60x60px.</param>
        public Logos(string Small = null, string Medium = null)
        {
            this.Small = Small;
            this.Medium = Medium;
        }
        
        /// <summary>
        /// URL to logo of resolution 27x27px
        /// </summary>
        /// <value>URL to logo of resolution 27x27px</value>
        [DataMember(Name="small", EmitDefaultValue=false)]
        public string Small { get; set; }
        /// <summary>
        /// URL to logo of resolution 60x60px
        /// </summary>
        /// <value>URL to logo of resolution 60x60px</value>
        [DataMember(Name="medium", EmitDefaultValue=false)]
        public string Medium { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Logos {\n");
            sb.Append("  Small: ").Append(Small).Append("\n");
            sb.Append("  Medium: ").Append(Medium).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as Logos);
        }

        /// <summary>
        /// Returns true if Logos instances are equal
        /// </summary>
        /// <param name="other">Instance of Logos to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Logos other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Small == other.Small ||
                    this.Small != null &&
                    this.Small.Equals(other.Small)
                ) && 
                (
                    this.Medium == other.Medium ||
                    this.Medium != null &&
                    this.Medium.Equals(other.Medium)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Small != null)
                    hash = hash * 59 + this.Small.GetHashCode();
                if (this.Medium != null)
                    hash = hash * 59 + this.Medium.GetHashCode();
                return hash;
            }
        }
    }

}
