/* 
 * Amadeus Travel Innovation Sandbox
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace IO.Swagger.Model
{
    /// <summary>
    /// RailService
    /// </summary>
    [DataContract]
    public partial class RailService :  IEquatable<RailService>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RailService" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected RailService() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="RailService" /> class.
        /// </summary>
        /// <param name="DestinationStationId">ID of the destination rail station. (required).</param>
        /// <param name="Services">An array of departure times at which trains depart from the origin station to this destination station. Times are in the ISO 8601 YYYY-MM-DDTHH:mm format. (required).</param>
        public RailService(string DestinationStationId = null, List<string> Services = null)
        {
            // to ensure "DestinationStationId" is required (not null)
            if (DestinationStationId == null)
            {
                throw new InvalidDataException("DestinationStationId is a required property for RailService and cannot be null");
            }
            else
            {
                this.DestinationStationId = DestinationStationId;
            }
            // to ensure "Services" is required (not null)
            if (Services == null)
            {
                throw new InvalidDataException("Services is a required property for RailService and cannot be null");
            }
            else
            {
                this.Services = Services;
            }
        }
        
        /// <summary>
        /// ID of the destination rail station.
        /// </summary>
        /// <value>ID of the destination rail station.</value>
        [DataMember(Name="destination_station_id", EmitDefaultValue=false)]
        public string DestinationStationId { get; set; }
        /// <summary>
        /// An array of departure times at which trains depart from the origin station to this destination station. Times are in the ISO 8601 YYYY-MM-DDTHH:mm format.
        /// </summary>
        /// <value>An array of departure times at which trains depart from the origin station to this destination station. Times are in the ISO 8601 YYYY-MM-DDTHH:mm format.</value>
        [DataMember(Name="services", EmitDefaultValue=false)]
        public List<string> Services { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RailService {\n");
            sb.Append("  DestinationStationId: ").Append(DestinationStationId).Append("\n");
            sb.Append("  Services: ").Append(Services).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as RailService);
        }

        /// <summary>
        /// Returns true if RailService instances are equal
        /// </summary>
        /// <param name="other">Instance of RailService to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RailService other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.DestinationStationId == other.DestinationStationId ||
                    this.DestinationStationId != null &&
                    this.DestinationStationId.Equals(other.DestinationStationId)
                ) && 
                (
                    this.Services == other.Services ||
                    this.Services != null &&
                    this.Services.SequenceEqual(other.Services)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.DestinationStationId != null)
                    hash = hash * 59 + this.DestinationStationId.GetHashCode();
                if (this.Services != null)
                    hash = hash * 59 + this.Services.GetHashCode();
                return hash;
            }
        }
    }

}
