/* 
 * Amadeus Travel Innovation Sandbox
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Reservation
    /// </summary>
    [DataContract]
    public partial class Reservation :  IEquatable<Reservation>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Reservation" /> class.
        /// </summary>
        /// <param name="FlightTickets">FlightTickets.</param>
        /// <param name="UnticketedFlights">The flight itineraries in this reservation that have not yet been ticketed or priced..</param>
        /// <param name="Cars">The rental cars reserved..</param>
        /// <param name="Hotels">The hotel room bookings in this reservation..</param>
        /// <param name="Others">Free text information to represent other travel items that may be considered part of the travel itinerary in this reservation..</param>
        public Reservation(FlightTicket FlightTickets = null, List<FlightReservationBound> UnticketedFlights = null, List<CarReservation> Cars = null, List<HotelReservation> Hotels = null, List<OtherReservation> Others = null)
        {
            this.FlightTickets = FlightTickets;
            this.UnticketedFlights = UnticketedFlights;
            this.Cars = Cars;
            this.Hotels = Hotels;
            this.Others = Others;
        }
        
        /// <summary>
        /// Gets or Sets FlightTickets
        /// </summary>
        [DataMember(Name="flight_tickets", EmitDefaultValue=false)]
        public FlightTicket FlightTickets { get; set; }
        /// <summary>
        /// The flight itineraries in this reservation that have not yet been ticketed or priced.
        /// </summary>
        /// <value>The flight itineraries in this reservation that have not yet been ticketed or priced.</value>
        [DataMember(Name="unticketed_flights", EmitDefaultValue=false)]
        public List<FlightReservationBound> UnticketedFlights { get; set; }
        /// <summary>
        /// The rental cars reserved.
        /// </summary>
        /// <value>The rental cars reserved.</value>
        [DataMember(Name="cars", EmitDefaultValue=false)]
        public List<CarReservation> Cars { get; set; }
        /// <summary>
        /// The hotel room bookings in this reservation.
        /// </summary>
        /// <value>The hotel room bookings in this reservation.</value>
        [DataMember(Name="hotels", EmitDefaultValue=false)]
        public List<HotelReservation> Hotels { get; set; }
        /// <summary>
        /// Free text information to represent other travel items that may be considered part of the travel itinerary in this reservation.
        /// </summary>
        /// <value>Free text information to represent other travel items that may be considered part of the travel itinerary in this reservation.</value>
        [DataMember(Name="others", EmitDefaultValue=false)]
        public List<OtherReservation> Others { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Reservation {\n");
            sb.Append("  FlightTickets: ").Append(FlightTickets).Append("\n");
            sb.Append("  UnticketedFlights: ").Append(UnticketedFlights).Append("\n");
            sb.Append("  Cars: ").Append(Cars).Append("\n");
            sb.Append("  Hotels: ").Append(Hotels).Append("\n");
            sb.Append("  Others: ").Append(Others).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as Reservation);
        }

        /// <summary>
        /// Returns true if Reservation instances are equal
        /// </summary>
        /// <param name="other">Instance of Reservation to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Reservation other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.FlightTickets == other.FlightTickets ||
                    this.FlightTickets != null &&
                    this.FlightTickets.Equals(other.FlightTickets)
                ) && 
                (
                    this.UnticketedFlights == other.UnticketedFlights ||
                    this.UnticketedFlights != null &&
                    this.UnticketedFlights.SequenceEqual(other.UnticketedFlights)
                ) && 
                (
                    this.Cars == other.Cars ||
                    this.Cars != null &&
                    this.Cars.SequenceEqual(other.Cars)
                ) && 
                (
                    this.Hotels == other.Hotels ||
                    this.Hotels != null &&
                    this.Hotels.SequenceEqual(other.Hotels)
                ) && 
                (
                    this.Others == other.Others ||
                    this.Others != null &&
                    this.Others.SequenceEqual(other.Others)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.FlightTickets != null)
                    hash = hash * 59 + this.FlightTickets.GetHashCode();
                if (this.UnticketedFlights != null)
                    hash = hash * 59 + this.UnticketedFlights.GetHashCode();
                if (this.Cars != null)
                    hash = hash * 59 + this.Cars.GetHashCode();
                if (this.Hotels != null)
                    hash = hash * 59 + this.Hotels.GetHashCode();
                if (this.Others != null)
                    hash = hash * 59 + this.Others.GetHashCode();
                return hash;
            }
        }
    }

}
